const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0A84FF",
    background: "#F2F2F7",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E5E5EA",
    secondaryForeground: "#1a1a1a",
    muted: "#E5E5EA",
    mutedForeground: "#8E8E93",
    accent: "#0A84FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#C6C6C8",
    input: "#E5E5EA",
  },
  dark: {
    text: "#F5F5F7",
    tint: "#0A84FF",
    background: "#000000",
    foreground: "#F5F5F7",
    card: "#111111",
    cardForeground: "#F5F5F7",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C1E",
    secondaryForeground: "#F5F5F7",
    muted: "#1C1C1E",
    mutedForeground: "#8E8E93",
    accent: "#0A84FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#1C1C1E",
  },
  radius: 12,
};

export const FUNCTION_COLORS = [
  "#0A84FF",
  "#30D158",
  "#FF9F0A",
  "#FF375F",
  "#BF5AF2",
  "#5AC8FA",
];

export default colors;
